export const SET_NUMBER = "SET_NUMBER";
export const SET_OPERATOR = "SET_OPERATOR";
export const CLEAR_INPUTS = "CLEAR_INPUTS";

export const RECALL_MEMORY = "RECALL_MEMORY";
export const CLEAR_MEMORY = "CLEAR_MEMORY";
export const ADD_TO_MEMORY = "ADD_TO_MEMORY";
export const SUBTRACT_FROM_MEMORY = "SUBTRACT_FROM_MEMORY";

export const CALCULATE = "CALCULATE";
